cspell/.cspell.json

The product webpage of  "G30Es-Li" <https://www.yamaha-motor.co.jp/golfcar/lineup/g30es-li/>

Add `esli` from the product name "G30Es-Li"

---

cspell/.cspell.json

The word is used as `std::vector<double> px, py, pz, pyaw, tlx, taz, alx, aaz;`.

Add the word `pyaw` used in motion_velocity_optimizer_utils.cpp

---

cspell/.cspell.json

An option of `tree` command.
> $ man tree
> ..snip..
> --noreport
>   Omits printing of the file and directory report at the end of the tree listing.

Add `noreport` into the dictionary

---

cspell/.cspell.json

https://github.com/ros-perception/vision_opencv/blob/906d326c146bd1c6fbccc4cd1268253890ac6e1c/image_geometry/include/image_geometry/pinhole_camera_model.h#L121
image_geometryの関数群に含まれるunrectifyを追加しました。

Add unrectify for image geometry

---

cspell/.cspell.json

I'll leave it to you whether to add this or not because we often misspell `arrange` as `arange`.

Add numpy function name `arange`

---

cspell/.cspell.json

Add `blindspots`

---

cspell/.cspell.json

xfer_format <https://github.com/Livox-SDK/livox_ros_driver/blob/ff656eeba6d4da132c98dd903ecc30a4dcf85e15/README.md#L117>

Add `xfer`

---

cspell/.cspell.json

For example, can be found in <https://github.com/NVIDIA/TensorRT/blob/master/samples/opensource/sampleNMT/cudaError.h>.

Add a CUDA-related word `callstr`

---

cspell/.cspell.json

対応内容
ntp_monitorのコマンド変更に伴い、以下の単語を追加
chrony
chronyc

add words for ntp_monitor

---

cspell/.cspell.json

Checking `*.pcd` produces a lot of false positives.

Ignore *.pcd from checking

---

cspell/.cspell.json

Checking package-lock.json produces a lot of false positives.

Ignore package-lock.json from checking

---

cspell/.cspell.json

<https://docs.codecov.com/docs/carryforward-flags>

Add `carryforward`

---

cspell/.cspell.json

multiline: for example <https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/RegExp/multiline>

Add `multiline`

---

cspell/.cspell.json

evenodd: <https://developer.mozilla.org/en-US/docs/Web/SVG/Attribute/fill-rule#usage_notes>

Add `evenodd`

---

cspell/.cspell.json

Ignore person's names and misc. For example:
.hpp, .cpp
- `TODO(John Smith)`
.md
- `(Contribution by John Smith)`
- `See [here](#acquirepositionaction)`
- `| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |`
- `gdown something-odd-hash-code or URL`
.rst
- `Merge branch 'master' into branch-name`
- `Contributors: John Smith, Foo Bar`

Add ignoreRegExpList

---

cspell/.cspell.json

LLVM OpenMP runtime <https://packages.ubuntu.com/en/bionic/libomp-dev>

Add `libomp`

---

cspell/.cspell.json

Added a word "bagkeeper " for a new ROS2 node name for TierIV internal use.

added "bagkeeper"

---

cspell/.cspell.json

Ignore Google Drive hashes in CMakeLists.txt.
For example:
```
download(foo.pt abcdefg)
download(bar.onnx abcdefg)
```

Ignore Google Drive hashes in CMakeLists.txt

---

cspell/.cspell.json

For example:
- `Vehicl...\n`
- `text-anchor="middle">maximum stopping distance consid...</text>\n`

Ignore abbreviated text in SVG files

---

cspell/.cspell.json

Add `awml` to pass spell check of https://github.com/tier4/autoware.proj/runs/4313109399?check_suite_focus=true .
`awml` means Autoware Machine Learning.  @scepter914

Add `awml`

---

cspell/.cspell.json

Sometimes we use `pilotauto` instead of `pilot.auto`.

Add a product name

---

cspell/.cspell.json

https://github.com/autowarefoundation/autoware-github-actions/runs/4961105288?check_suite_focus=true
I've checked it locally.

Ignore `uses: ` in GitHub Actions' workflow files

---

cspell/.cspell.json

https://github.com/autowarefoundation/autoware-github-actions/runs/4961105288?check_suite_focus=true
This is the format I designed. The specification is written [here](https://github.com/autowarefoundation/autoware-github-actions/blob/1f62cc13548aec50b1a333287ab5981fb4eb8b72/sync-files/README.md).
I've tested this locally.

Add ignore patterns for sync-files.yaml

---

cspell/.cspell.json

It is used [here](https://github.com/orhun/git-cliff/blob/848d8a587efd5f611a98b647b954c06938fac24a/config/cliff.toml#L58
) and also used like `topo maps`.
https://www.usgs.gov/programs/national-geospatial-program/us-topo-maps-america

Add `topo`

---

cspell/.cspell.json

https://github.com/autowarefoundation/autoware-documentation/runs/5054438985?check_suite_focus=true
`multiarch`: https://wiki.debian.org/Multiarch
`prestart`: a different notation of `pre-start`

Add container-related words

---

.cspell.json
cspell/.cspell.json

`wrapexcept` is used as `boost::wrapexcept`

feat: add wrapexcept

---

.cspell.json
cspell/.cspell.json

For patterns of `[org/repo-name](https://github.com/org/repo-name)`.
https://github.com/autowarefoundation/autoware-github-actions/pull/85/files#diff-b335630551682c19a781afebcf4d07bf978fb1f8ac04c6bf87428ed5106870f5R17

feat(ignoreRegExpList): ignore GitHub repository patterns

---

.cspell.json
cspell/.cspell.json

Added `CMakeLists.txt` file to ignore `TODO(username)` style error.
Related: https://github.com/autowarefoundation/autoware.universe/runs/5534066356?check_suite_focus=true#step:3:20

feat(ignoreRegExpList): add CMakeLists.txt

---

.cspell.json
cspell/.cspell.json

wstring is:
- [ROS 2 built-in-types](https://docs.ros.org/en/galactic/Concepts/About-ROS-Interfaces.html#field-types)
- Alias of `basic_string<wchar_t>` in C++

feat(words): add wstring

---

.cspell.json

This word appears in https://github.com/tier4/autoware.universe/blob/tier4/main/common/autoware_auto_common/include/common/types.hpp#L35

feat(words): add MISRA

---

.cspell.json

There are WARNINGs in this PR, so I added `XYZIRADRT`.
PR:
https://github.com/autowarefoundation/autoware.universe/pull/907
spell-check result:
https://github.com/autowarefoundation/autoware.universe/runs/6446390836?check_suite_focus=true

feat(words): add XYZIRADRT

---

.cspell.json

The official name of ros2 humble is Humble Hawksbill, but Hawksbill was caught by spell check, so I added it.
https://docs.ros.org/en/rolling/Releases/Release-Humble-Hawksbill.html

feat: add hawksbill

---

.cspell.json

[`mkdocstrings`](https://github.com/mkdocstrings/mkdocstrings) is one of commonly-used Python package.  
It generates API list from docstrings embedded in Python-based source code.
Signed-off-by: Takayuki AKAMINE <takayuki.akamine@tier4.jp>

feat(words): add mkdocstrings

---

.cspell.json

I couldn't find the format spec, but I've tested this with my file.

feat(overrides/svg): ignore inkscape patterns

---

.cspell.json

Add "AWSIM" to fix spell check CI failures for the AWSIM tutorial PR: 
https://github.com/autowarefoundation/autoware-documentation/pull/169
Signed-off-by: Lalith Vipulananthan <lalith.vipulananthan@tier4.jp>

feat(words): add awsim

---

.cspell.json

`liblttng` is regarded as a misspelled words, and  is used in [rosdep](https://github.com/ros/rosdistro/blob/e6c5b8a9f5c58b09434f9de30d8a95add9a7c0cc/rosdep/base.yaml#L3934-L3941).
`liblttng` is currently used in CARET.
https://github.com/tier4/CARET_trace/blob/cac487a8c5e55960ffe5ec93179a7565e13fb62e/CARET_trace/package.xml#L23

feat(words): add liblttng

---

.cspell.json

I've tested the behavior with the following patterns.
```json
"@tier4/foobar": "^0.1.2",
"esbuild": "^0.15.3",
```

feat(package.json/ignoreRegExpList): ignore patterns of dependencies

---

.cspell.json

It's used in the license notation of Leo Drive.
https://github.com/autowarefoundation/autoware.universe/pull/1138#discussion_r902409808
```
Copyright 2022 Leo Drive Teknoloji A.Ş.
```

feat(words): add Teknoloji

---

.cspell.json

The word `adapi` is used for packages related to AD API.

feat: add adapi

---

.cspell.json

I added machine learning words used in the package to be released at the end of September 2022.
APH stands for average precision weighted by heading.
maph stands for mean APH
aphs stands for array of APH
It is proposed in the Waymo's dataset and is explained in the following paper.
https://arxiv.org/pdf/2004.08745.pdf

feat: add machine learning word

---

.cspell.json

Signed-off-by: hsgwa <19860128+hsgwa@users.noreply.github.com>
addopts : https://docs.pytest.org/en/6.2.x/customize.html#tox-ini
- "addopts" is a keyword used by pytest configuration.
@kenji-miyake Please review it, best.

feat(word): add addopts

---

.cspell.json

The current setting didn't work with https://github.com/autowarefoundation/autoware.universe/blob/1a5403d564d203d0d2251a3b454e8aa78385cc6d/sensing/pointcloud_preprocessor/docs/image/vector_map_inside_area_filter_overview.svg?short_path=15feb3e.
Without this PR:
```console
❯ cspell ./sensing/pointcloud_preprocessor/docs/image/vector_map_inside_area_filter_overview.svg
1/1 ./sensing/pointcloud_preprocessor/docs/image/vector_map_inside_area_filter_overview.svg 109715.85ms X
/home/kenji/ghq/github.com/autowarefoundation/autoware.universe/sensing/pointcloud_preprocessor/docs/image/vector_map_inside_area_filter_overview.svg:11:387 - Unknown word (UAUEV)
/home/kenji/ghq/github.com/autowarefoundation/autoware.universe/sensing/pointcloud_preprocessor/docs/image/vector_map_inside_area_filter_overvie …
```

fix(svg/ignoreRegExpList): fix the id pattern

---

.cspell.json

There were several patterns other than `PointXYZ*`.
https://github.com/tier4/autoware-spell-check-dict/pull/410#issuecomment-1322897656

feat(ignoreRegExpList): fix PointXYZ patterns

---

.cspell.json

Signed-off-by: Kotaro Yoshimoto <pythagora.yoshimoto@gmail.com>
spell-checking is effective for miss spellings you can fix.
But, CHANGELOG.rst is based on commit messges and  fixing them is  　falsification for history of repository.
(and, some CHANGELOG.rst has many miss spellings. e.g. [this CHANGELOG.rst](https://github.com/autowarefoundation/autoware.universe/blob/main/sensing/geo_pos_conv/CHANGELOG.rst) has 15 cspell errors )
So, I think spell-checking for CHANGELOG.rst is not nessesary.
I welcome comments from other perspectives!

feat(ignorePaths): ignore CHANGELOG.rst

---

.cspell.json

Signed-off-by: Kotaro Yoshimoto <pythagora.yoshimoto@gmail.com>
This pull request adds an ignore pattern for URL encoded characters that makes many cspell errors in svg files.
the examples of cspell error source and the errors are below
```svg
<span style="color: rgba(0, 0, 0, 0); font-family: monospace; font-size: 0px; text-align: start;">
%3CmxGraphModel%3E%3Croot%3E%3CmxCell%20id%3D%220%22%2F%3E%3CmxCell%20id%3D%221%22%20parent%3D%220%22%2F%3E%3CmxCell%20id%3D%222%22%20value%3D%22attention_range%22%20style%3D%22text%3Bhtml%3D1%3BstrokeColor%3Dnone%3BfillColor%3Dnone%3Balign%3Dcenter%3BverticalAlign%3Dmiddle%3BwhiteSpace%3Dwrap%3Brounded%3D0%3BfontSize%3D20%3BfontStyle%3D2%22%20vertex%3D%221%22%20parent%3D%221%22%3E%3CmxGeometry%20x%3D%22531%22%20y%3D%221610%22%20width%3D%22210%22%20heig …
```

feat(ignoreRegExpList): ignore URL encoded characters for svg file

---

.cspell.json

To support the patterns like https://github.com/tier4/perception_ecu_container/blob/616918635ab33cf0c003c21a4dec499217f9457e/docker/Dockerfile#L6.
Related: https://github.com/tier4/autoware-spell-check-dict/pull/431

feat(languageSettings/dockerfile): ignore the `FROM` pattern

---

.cspell.json

| word | target | |
| --- | --- | --- |
| Josefin | svg | part of "Josefin Sans", a font name |
| mtext | svg | https://developer.mozilla.org/en-US/docs/Web/MathML/Element/mtext |
| munder | svg | https://developer.mozilla.org/en-US/docs/Web/MathML/Element/munder |
| munderover | svg | https://developer.mozilla.org/en-US/docs/Web/MathML/Element/munderover |
| mtable | svg | https://developer.mozilla.org/en-US/docs/Web/MathML/Element/mtable |
| mlabeledtr | svg | https://udn.realityripple.com/docs/Web/MathML/Element/mlabeledtr |
| mfrac | svg | https://developer.mozilla.org/en-US/docs/Web/MathML/Element/mfrac |
| mphantom | svg | https://developer.mozilla.org/en-US/docs/Web/MathML/Element/mphantom |
| msup | svg | https://developer.mozilla.org/en-US/docs/Web/MathML/Element/msup |

feat(svg/ignoreRegExpList): add words

---

.cspell.json

Avoid matching `tparam` in `SetParameter`

refactor: avoid matching SetParameter

---

.cspell.json

Copyrights usually contain proper noun, which often causes false positives.
Example: https://github.com/tier4/CalibrationTools/blob/3ac4928e705e652ff114ea48a4dba046ff622ce0/sensor/docs/resource/KALIBR_LICENSE

feat(ignoreRegExpList): ignore copyright patterns

---

.cspell.json

https://code.visualstudio.com/brand
We must use `Visual Studio Code` or `VS Code`.

feat(flagWords): add VSCode

---

format_cspell_json/format_cspell_json.py

https://github.com/adamchainz/flake8-comprehensions/tree/d8d15cfd0846df1c611dfb1f214174bcb56a869d#c419-unnecessary-list-comprehension-in-anyall-prevents-short-circuiting---rewrite-as-a-generator

style: apply pre-commit fixes

---

.cspell.json

https://tier4.jp/en/media/detail/?sys_id=4nwhhCgZGuFnqt9MuveSzp&category=DOCUMENTS
We must use `TIER IV` or `tier4` (allowed in URLs).

feat(flagWords): add incorrect patterns of `TIER IV`

---

format_cspell_json/format_cspell_json.py

To prevent `TierIV` and `TIERIV` from always swapping.
The key is from https://github.com/tier4/cspell-dicts/blob/3023f03f46209f4adaf179d71185b2289ceb9346/tier4_cspell_dicts/format_words.py#L11.

ci(format_cspell_json): fix sorting

---

.cspell.json

Found in https://github.com/autowarefoundation/autoware-documentation/pull/367/files.

feat(svg/ignoreRegExpList): ignore fill

---

.cspell.json

Some svg files include a word "truetype" to identify the font name [TrueType](https://en.wikipedia.org/wiki/TrueType).

feat: add truetype for svg

---

.cspell.json

Reverts tier4/autoware-spell-check-dict#682
Because it's flag word.
https://github.com/tier4/autoware-spell-check-dict/blob/main/.cspell.json#L256

fix(words): remove flag word "Github"

---

.cspell.json

Fixed https://github.com/autowarefoundation/autoware/actions/runs/9091082555/job/24985001467?pr=4721
https://docs.docker.com/build/cache/

fix: add buildcache to .cspell.json

---

.github/workflows/add-word.yaml

Since not a few people submit PRs by providing only a link with their own usage only, I decided to add a notation to the PR template like below
---
TODO: Update this comment and add some reference links.
your usage of the word: [link of github or something]()
The documentation for the word: [link for word documentation]()
> [!NOTE]
> To get approval, you need to show external documentation proving that the word is not your own creation, but is common in the public and industry.
> Please check [CONTRIBUTING.md](https://github.com/tier4/autoware-spell-check-dict/blob/main/CONTRIBUTING.md) for detail.

docs: add notation in pull-request template
