tier4/autoware-spell-check-dict

- cspell/.cspell.json
It's intentionally duplicated and not sorted for CI test.
Please merge #2 first.
> Add logsim

- cspell/.cspell.json
> Add an ndt_omp-related word to the dictionary

- cspell/.cspell.json
> Add MuSSP-related word to the dictionary

- cspell/.cspell.json
> [1] Anderson, B. D. O., & Moore, J. B. (1979). Optimal filtering. Englewood Cliffs, NJ: Prentice-Hall.
> Add `Englewood` from the book information

- cspell/.cspell.json
:tada:
* <http://docs.ros.org/en/galactic/Releases/Release-Galactic-Geochelone.html>
* <https://en.wikipedia.org/wiki/Geochelone>
> Add `Geochelone`, the name of the latest ROS 2 distribution

- cspell/.cspell.json
- https://hub.docker.com/r/rostooling/setup-ros-docker
- https://github.com/autowarefoundation/ros2_socketcan
- https://github.com/autowarefoundation/ros2_socketcan/blob/main/.github/workflows/build_test.yml
> Add `rostooling` and `socketcan` from ros2 repository names

- cspell/.cspell.json
To allow the word found in `// TODO(hiro-ya-iv)`.
> Add a person's name `hiro`

- cspell/.cspell.json
```
_______________________
< Add the word 'cowsay' >
-----------------------
\   ^__^
\  (oo)\_______
(__)\       )\/\
||----w |
||     ||
```
> Add `cowsay` into the dictionary

- cspell/.cspell.json
`xargs` is a common shell command.
> Add `xargs` into the dictionary

- cspell/.cspell.json
* imdecode <https://docs.opencv.org/master/d4/da8/group__imgcodecs.html#ga26a67788faa58ade337f8d28ba0eb19e>
* imencode <https://docs.opencv.org/master/d4/da8/group__imgcodecs.html#ga461f9ac09887e47797a54567df3b8b63>
> Add the words related to OpenCV

- cspell/.cspell.json
> Add `XYZRT` from PointCloud type

- cspell/.cspell.json
https://github.com/tier4/pointcloud_to_laserscan/pull/1
http://www.6d-vision.com/aktuelle-forschung/stixel-world
> Add Computer Vision related word `stixel`

- cspell/.cspell.json
See <http://wiki.ros.org/ja/roslaunch/XML>.
> Add a roslaunch-related word `optenv`

- cspell/.cspell.json
- <https://docs.opencv.org/4.5.2/df/d3d/tutorial_py_inpainting.html>
> Add the word `inpaint`

- cspell/.cspell.json
<https://pre-commit.com/#updating-hooks-automatically>
> Add `autoupdate`

- cspell/.cspell.json
See <https://github.com/pre-commit/pre-commit-hooks#trailing-whitespace>
> Add `linebreak`

- cspell/.cspell.json
- Axisf <https://eigen.tuxfamily.org/dox/classEigen_1_1AngleAxis.html>
> Add `Axisf`

- cspell/.cspell.json
`calib`: Abbreviation of calibration.
> Add `calib`

- cspell/.cspell.json
FastCRC <https://github.com/FrankBoesing/FastCRC>
> Add `FASTCRC`

- cspell/.cspell.json
> Add `rostopics`

- cspell/.cspell.json
https://en.wikipedia.org/wiki/Bresenham%27s_line_algorithm
> Add a person's name `Bresenham`

- cspell/.cspell.json
> Add `robotec`

- cspell/.cspell.json
ECEF: https://en.wikipedia.org/wiki/ECEF
markdownlint: https://github.com/DavidAnson/markdownlint
> Add words `ECEF` and `markdownlint`

- cspell/.cspell.json
https://fonts.google.com/specimen/Noto+Sans+JP
Every time we run the spell check, this word suffers us. :pleading_face: 
So I'd like to add this. :pray:
> Add font name `Noto`

- cspell/.cspell.json
Forgot to add this in #76.
Zhou: <https://openaccess.thecvf.com/content/CVPR2021/papers/Yin_Center-Based_3D_Object_Detection_and_Tracking_CVPR_2021_paper.pdf>
> Add `Zhou`

- cspell/.cspell.json
keepdim <https://pytorch.org/docs/stable/generated/torch.sum.html>
> Add `keepdim`

- cspell/.cspell.json
pmatrix: a TeX package <https://www.tutorialspoint.com/tex_commands/pmatrix.htm>
> Add `pmatrix`

- cspell/.cspell.json
https://github.com/peter-evans/enable-pull-request-automerge
> Add a word `automerge`

- cspell/.cspell.json
> Add `RMSE`

- cspell/.cspell.json
<https://en.cppreference.com/w/cpp/utility/optional/nullopt>
> Add `nullopt`

- cspell/.cspell.json
<https://docs.opencv.org/4.5.2/d9/d0c/group__calib3d.html#ga69f2545a8b62a6b0fc2ee060dc30559d>
> Add `undistort`

- cspell/.cspell.json
Sorry I remake PR.
It stands for X, Y, Z, Intensity, Ring, Azimuth, Distance and Timestamp
> add XYZIRADT

- cspell/.cspell.json
Short form of `packages` like https://github.com/ros-simulation/gazebo_ros_pkgs
> Add word `pkgs`

- cspell/.cspell.json
kyabe <https://github.com/kyabe2718>
> Add user id `kyabe`

- cspell/.cspell.json
https://en.wikipedia.org/wiki/ECMAScript
> Add `ECMAScript`

- cspell/.cspell.json
Add one new word "FMEA".
https://ja.wikipedia.org/wiki/FMEA
https://en.wikipedia.org/wiki/Failure_mode_and_effects_analysis
> Add the word FMEA

- cspell/.cspell.json
- Mizushima: family name
- Hayato:       first name
- bibtex:        formatting tool for references of papers <http://tug.org/bibtex/>
- XYZRPY:   X, Y, Z, Roll, Pitch, Yaw
- VeloView:   The Velodyne Lidar Viewer based on Paraview Lidar <https://www.paraview.org/veloview/>
> add some spells

- cspell/.cspell.json
roboteq: company name https://www.roboteq.com/index.php
MSCL: `The MicroStrain Communication Library` https://github.com/LORD-MicroStrain/MSCL
> add `roboteq` and `MSCL`

- cspell/.cspell.json
microstrain: company name https://www.microstrain.com/
> add microstrain

- cspell/.cspell.json
- sort_cspell_json.sh
Signed-off-by: Takagi, Isamu <isamu.takagi@tier4.jp>
svgファイルでエンコードされた文字列を検出してしまうのを抑制する。
> Add ignore setting of svg content attribute

- cspell/.cspell.json
FTTI (Fault Tolerant Time Interval)
FHTI (Fault Handling Time Interval)
> Add the words FTTI and FHTI

- cspell/.cspell.json
- codeinclude <https://github.com/rnorth/mkdocs-codeinclude-plugin>
> Add `codeinclude`

- cspell/.cspell.json
https://linuxjm.osdn.jp/html/LDP_man-pages/man7/signal.7.html
Added only currently used words.
> Add Linux signal related words

- cspell/.cspell.json
https://numpy.org/doc/stable/reference/generated/numpy.ndarray.astype.html
> Add numpy function name `astype`

- cspell/.cspell.json
https://linuxjm.osdn.jp/html/util-linux/man1/getopt.1.html
> Add linux command `getopt`

- cspell/.cspell.json
https://www.flir.jp/products/blackfly-s-gige/
> Add FLIR, Blackfly

- cspell/.cspell.json
>  Update .cspell.json add name

- cspell/.cspell.json
https://en.wikipedia.org/wiki/General-purpose_input/output
> Add `gpio`

- cspell/.cspell.json
> Add an engineer's name

- cspell/.cspell.json
> Add `Yushi`

- cspell/.cspell.json
Roboto <https://fonts.google.com/specimen/Roboto>
> Add a font name `Roboto`

- cspell/.cspell.json
- xaxis -> https://plotly.com/python/reference/layout/xaxis/
- yaxis -> https://plotly.com/python/reference/layout/yaxis/
- showlegend -> https://plotly.com/python/legend/#:~:text=fourth-,Showing%20and%20Hiding%20the%20Legend,-By%20default%20the
> Add plotly words xaxis, yaxis, showlegend

- cspell/.cspell.json
skinparam <https://plantuml.com/en/skinparam>
> Add `skinparam`

- cspell/.cspell.json
frechet <https://en.wikipedia.org/wiki/Fr%C3%A9chet_distribution>
> Add `frechet`

- cspell/.cspell.json
https://en.wikipedia.org/wiki/Ackermann_steering_geometry
> Add `Ackermann`

- cspell/.cspell.json
kinshicho：錦糸町、S1の実証実験で走行するエリアです
> add kinshicho

- cspell/.cspell.json
Added docker related words to resolve following warnings:
https://github.com/autowarefoundation/AutowareTestCoreRepository/actions/runs/1439168219
> Add docker related words

- cspell/.cspell.json
fastrtps <https://index.ros.org/r/fastrtps/>
> Add `fastrtps`

- cspell/.cspell.json
Add `mountpoint` .
related to https://github.com/tier4/autoware_launcher.eva/runs/4207678019?check_suite_focus=true#step:4:70 
Meaning
https://en.wikipedia.org/wiki/Mount_(computing)
https://e-words.jp/w/%E3%83%9E%E3%82%A6%E3%83%B3%E3%83%88%E3%83%9D%E3%82%A4%E3%83%B3%E3%83%88.html
> Add `mountpoint`

- cspell/.cspell.json
Use for software name to overwrite some data.
> Add overwriter

- cspell/.cspell.json
shfmt: https://github.com/mvdan/sh#shfmt
autofix: https://pre-commit.ci/#configuration
> Add CI-related words

- cspell/.cspell.json
pybind <https://github.com/pybind/pybind11>
> Add `pybind`

- cspell/.cspell.json
https://www.gnu.org/software/bash/manual/bash.html#Reserved-Words
> Add Bash-related words

- cspell/.cspell.json
> add takagi

- cspell/.cspell.json
https://docs.docker.com/engine/install/ubuntu/#uninstall-old-versions
> Add container-related words

- cspell/.cspell.json
https://www.gnupg.org/documentation/manuals/gnupg/Operational-GPG-Commands.html
> Add GPG-related word

- cspell/.cspell.json
https://pypi.org/project/pytest-rerunfailures/
https://docs.ros.org/en/galactic/Installation/Ubuntu-Development-Setup.html#install-development-tools-and-ros-tools
> Add Python package's name `rerunfailures`

- cspell/.cspell.json
https://en.wikipedia.org/wiki/Server_Base_System_Architecture
> Add ARM-related word `sbsa`

- cspell/.cspell.json
> Add `wasim`

- cspell/.cspell.json
https://www.contributor-covenant.org/version/2/1/code_of_conduct/
> Add `socio`

- cspell/.cspell.json
Resolves https://github.com/autowarefoundation/autoware-github-actions/pull/49#discussion_r799229288
> add the word ctest

- cspell/.cspell.json
https://github.com/adrienverge/yamllint
> Add yamllint

- cspell/.cspell.json
The `rsplit` is a python method.
> feature: add `rsplit`

- cspell/.cspell.json
vercel: https://github.com/vercel/ncc
> Update for javascript

- cspell/.cspell.json
- sort_cspell_json.sh
Dropped here.
https://github.com/tier4/autoware-spell-check-dict/pull/207/commits/6d01b41b40569a4940cb92721c50ff4655bf28af
> Keep ignoreRegExpList

- cspell/.cspell.json
https://github.com/tier4/autoware-spell-check-dict/runs/5156567275?check_suite_focus=true
> Add words in sort_cspell_json.sh

- .cspell.json
> feat: add tpdo

- .cspell.json
- cspell/.cspell.json
> feat(words): add ccache

- .cspell.json
- cspell/.cspell.json
> feat: add netplan

- .cspell.json
- cspell/.cspell.json
https://en.wikipedia.org/wiki/COLLADA
> feat(words): add COLLADA

- .cspell.json
- cspell/.cspell.json
https://docs.ansible.com/ansible/latest/collections/ansible/builtin/blockinfile_module.html#ansible-collections-ansible-builtin-blockinfile-module
> feat(words): add blockinfile

- .cspell.json
- cspell/.cspell.json
modeset is used in linux kernel
> feat(words): add `modeset`

- .cspell.json
- cspell/.cspell.json
https://github.com/gabrielcnr/pytest-datadir
> feat(words): add datadir

- .cspell.json
- cspell/.cspell.json
I'd like to add `uncore` which is Intel's microprocessor function.
https://en.wikipedia.org/wiki/Uncore
Signed-off-by: Takayuki AKAMINE <takayuki.akamine@tier4.jp>
> feat(words): add uncore

- .cspell.json
- cspell/.cspell.json
Found in https://github.com/kenji-miyake/setup-git-cliff/pull/15/files.
Before:
After:
> feat(ignoreRegExpList): ignore the pattern of GitHub Actions in Markdown files

- .cspell.json
- cspell/.cspell.json
https://github.com/rigtorp/udpreplay
> feat(words): add udpreplay

- .cspell.json
- cspell/.cspell.json
spell-checkの辞書にgdriveを追加
Signed-off-by: tomoya.kimura <tomoya.kimura@tier4.jp>
> feat(words): add gdrive

- .cspell.json
- cspell/.cspell.json
add jetpack, jetson library name
https://developer.nvidia.com/embedded/jetpack
https://github.com/tier4/autoware_ecu_system_setup/runs/5565879935?check_suite_focus=true
> feat: add jetpack

- .cspell.json
https://manpages.debian.org/stretch/apt/apt-mark.8.ja.html
https://github.com/autowarefoundation/autoware-documentation/pull/76
> feat(words): add unhold

- .cspell.json
Words in this PR used in below.
capwords: python function name
https://github.com/tier4/logsim/blob/b429929c4568d0b2178068ebcc99410db1d8f256/logsim/logsim/launch_common.py#L265
NVTL: new localization likelihood
https://github.com/tier4/logsim/blob/5d39be501470446cc052b1df0f2b856031d479af/logsim/include/logsim/localization_evaluator_component.hpp#L267
> feat: add words used in logsim

- format_cspell_json/format_cspell_json.py
- tests/test_format_cspell_json/.cspell.answer.json
- tests/test_format_cspell_json/.cspell.input.json
Added Markdown settings for https://github.com/tier4/autoware-spell-check-dict/pull/265.
Also, refactored some code, and fix some minor bugs that I found during the work.
> ci(format_cspell_json): refactor code

- .cspell.json
https://pypi.org/project/beautifulsoup4/
> feat(words): add beautifulsoup

- .cspell.json
https://flask.palletsprojects.com/en/2.1.x/api/#flask.json.jsonify
> feat(words): add jsonify

- .cspell.json
http://wiki.ros.org/orocos_kdl
> feat(words): add orocos

- .cspell.json
> feat(words): add cgal

- .cspell.json
https://github.com/autowarefoundation/autoware_common/pull/67
> feat(words): add DROS

- .cspell.json
https://github.com/autowarefoundation/autoware/blob/2e551c78bbe955d1bc9fecd26deffcb0cfbc3c18/ansible/galaxy.yml
> feat(overrides): ignore name pattern of galaxy.yml

- .cspell.json
https://github.com/tier4/jetson_launcher/runs/6450168959?check_suite_focus=true
https://github.com/Megvii-BaseDetection/YOLOX
> feat(words): add new yolo model

- .cspell.json
I added function cprint included in python termcolor.
https://pypi.org/project/termcolor/
> feat: add python termcolor function name "cprint"

- .cspell.json
https://docs.microsoft.com/ja-jp/typography/font-list/tahoma
Found in https://github.com/autowarefoundation/autoware-documentation/pull/124/files.
> feat(words): add Tahoma

- .cspell.json
> feat(words): add ANYbotics

- .cspell.json
Add words related curses.
- "NPAGE"
- "PPAGE"
- https://docs.python.org/3/library/curses.html#constants
> feat(words): add NPAGE and PPAGE for curses

- .cspell.json
I added words from ros2_numpy
https://github.com/Box-Robotics/ros2_numpy
https://numpy.org/doc/stable/reference/generated/numpy.ndarray.html
> feat(words): add ros_numpy words

- .cspell.json
I added setsockopt.
- setsockopt: [getsockopt and setsockopt in ubuntu manual page](https://manpages.ubuntu.com/manpages/bionic/en/man2/getsockopt.2.html)
> feat: add setsocketopt

- .cspell.json
Adding "AISAN" to word list for [autowarefoundation/autoware#140](https://github.com/autowarefoundation/autoware-documentation/pull/140)
Signed-off-by: Lalith Vipulananthan <lalith.vipulananthan@tier4.jp>
> feat(words): add aisan

- .cspell.json
vulkan: https://ja.wikipedia.org/wiki/Vulkan_(API)
glvnd: https://github.com/NVIDIA/libglvnd
Related PR: https://github.com/autowarefoundation/autoware/pull/2736
> feat(words): add vulkan words

- .cspell.json
https://en.wikipedia.org/wiki/Robotaxi
> A robotaxi, also known as robo-raxi
> feat(words): add robo

- .cspell.json
https://github.com/autowarefoundation/autoware/runs/7601818540?check_suite_focus=true#step:3:37
> feat(ignorePaths): ignore .clang-tidy

- .cspell.json
https://clang.llvm.org/extra/clang-tidy/#suppressing-undesired-diagnostics
> feat(words): add NOLINTNEXTLINE

- .cspell.json
OpsCons: Operations Concepts
Sometimes we write it in lowercase.
> feat(words): add opscons

- .cspell.json
https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/about-code-owners
> feat(words): add CODEOWNERS

- .cspell.json
https://en.wikipedia.org/wiki/Cheat_sheet
It's used in PlotJuggler.
https://github.com/facontidavide/PlotJuggler/blob/c559f915a726d759f4ba23e7153173ed7b34c90e/plotjuggler_app/mainwindow.ui#L1910
> feat(words): add cheetsheet

- .cspell.json
https://github.com/microsoft/pyright
> feat(words): add pyright

- .cspell.json
https://github.com/tier4/autoware-spell-check-dict/pull/322#issuecomment-1227310437
> fix(words): fix typo

- .cspell.json
ref: https://en.wikipedia.org/wiki/Akima_spline
https://github.com/autowarefoundation/autoware.universe/runs/7665045442?check_suite_focus=true
> chore: add Akima

- .cspell.json
https://pypi.org/project/pyflakes/
> fix(words): fix pyflake to pyflakes

- .cspell.json
pgrep reference is below.
https://ja.wikipedia.org/wiki/Pgrep
> feat(words): add pgrep

- .cspell.json
This PR adds logging related words.
Attributes list:
levelname, levelno : https://docs.python.org/ja/3/library/logging.html#logrecord-objects (**levelno** for the numeric value and **levelname** for the corresponding level name.)
> feat(words): add logging related words

- .github/workflows/add-word.yaml
It's useful if we can add a word from a workflow.
> ci: add add-word.yaml

- .github/workflows/add-word.yaml
Fixup for https://github.com/tier4/autoware-spell-check-dict/pull/339.
> ci(add-words): fix error

- .cspell.json
Attributes list:
https://ipywidgets.readthedocs.io/en/stable/
> feat(word): add ipywidgets

- .cspell.json
Add words used in the repository to be released at the end of September 2022
https://github.com/tier4/driving_log_replayer
> feat: add simulator word

- .cspell.json
multimethod: https://coady.github.io/multimethod/
> feat(word): add multimethod

- .cspell.json
caplog: https://docs.pytest.org/en/7.1.x/reference/reference.html?highlight=caplog#std-fixture-caplog
> feat(word): add caplog

- .cspell.json
timespec: https://cpprefjp.github.io/reference/ctime/timespec.html
> feat(word): add timespec

- .cspell.json
toggleable : https://docs.bokeh.org/en/latest/docs/reference/models/tools.html?highlight=toggleable#bokeh.models.CrosshairTool.toggleable
> feat(word): add toggleable

- .cspell.json
FaroCAN: FARO Series CANBUS Module
https://www.antzer-tech.com/can-bus-mini-pcie-card
> feat(words): add farocan

- .cspell.json
nftables: https://en.wikipedia.org/wiki/Nftables
@kenji-miyake Please review it, thanks.
> feat(words): add nftables

- .cspell.json
> feat(ignoreRegExpList): ignore ppa pattern

- .cspell.json
I guess it would be better than adding each word every time.
> feat(ignoreRegExpList): ignore PointXYZ types

- .cspell.json
Used here: https://github.com/tier4/perception_ecu_container/blob/89e7d6bc3683d0d82d6c051fc94e204a4aac8bee/ansible/roles/cyclonedds/templates/cyclonedds.xml.jinja2#L9
Related: #431
> feat(overrides/cyclonedds): ignore DontRoute

- .cspell.json
Related: https://github.com/tier4/cspell-dicts/pull/23
> feat(import): import new dicts "city-names" and "people-names"

- .github/workflows/add-word.yaml
> ci(add-word): fix labels

- .cspell.json
https://github.com/tier4/perception_ecu_container/actions/runs/4083607474/jobs/7039336593
> feat(words): add kitware

- .cspell.json
- Jira: https://developer.atlassian.com/platform/marketplace/atlassian-brand-guidelines-for-marketplace-partners/#atlassian-product-names
- ROS 2: https://www.ros.org/imgs/ROSBrandGuide.pdf / https://discourse.ros.org/t/should-i-put-a-space-between-ros-and-2/27949
- GitHub: https://docs.github.com/en/site-policy/github-terms/github-terms-for-additional-products-and-features
> feat(flagWords): add some brands

- README.md
add explanation for `add-word` workflow
> docs: add explanation for add-word workflow

- .cspell.json
https://docs.opencv.org/4.x/df/d2d/group__ximgproc.html
> feat: add ximgproc

- .cspell.json
Resampler
https://pandas.pydata.org/docs/reference/api/pandas.core.resample.Resampler.__iter__.html
> feat(words): add resampler

- .cspell.json
Add `nsswitch` (see https://en.wikipedia.org/wiki/Name_Service_Switch#nsswitch.conf)
> feat(words): add nsswitch

- .cspell.json
See https://github.com/autowarefoundation/autoware/actions/runs/6237022660/job/16929649433?pr=3848
> feat(words): add finetune

- .cspell.json
- `imageio` is a python library name
- https://github.com/imageio/imageio 
- `mimsave` is function name in `imageio`
- https://github.com/imageio/imageio/blob/085ce272ae33e9ee37da43d03bcca35bbb5d571d/imageio/__init__.py#L51
> feat(words): ignore imageio and mimsave from python files

- .cspell.json
Add "statustip" for rqt plugin xml.
https://wiki.ros.org/rqt/Tutorials/Create%20your%20new%20rqt%20plugin
> feat(words): add statustip for rqt plugin xml

- .cspell.json
Fixed: https://github.com/autowarefoundation/autoware/actions/runs/8811939509/job/24186731400?pr=4656
https://launchpad.net/~kisak/+archive/ubuntu/kisak-mesa
> fix: add kisak to .cspell.json

- .cspell.json
https://github.com/autowarefoundation/autoware.universe/actions/runs/9031229172/job/24817060462?pr=6883
> feat: add demi, DemiBold

- .cspell.json
Definition: https://doc.qt.io/qt-5/qtglobal.html#qreal-typedef
Related CI:
- https://github.com/autowarefoundation/autoware.universe/actions/runs/9039618808/job/24842740784?pr=6855
Related PR:
- https://github.com/autowarefoundation/autoware.universe/pull/6855
> feat(words): add qreal

- .cspell.json
https://github.com/soblin/matplotlibcpp17
for matplotlibcpp17
> feat(words): matplotlibcpp

- .cspell.json
> feat(words): add "repository" and "repositories"
